
STACK SEGMENT STACK 'STACK'  
    DW 32H DUP(0);
    STACK ENDS;
DATASG SEGMENT 'DAT'
    DATA_IN DB 25H,30H,50H,40H,60H
    COPY1 DB 5 DUP<?>
    DATASG ENDS;
CODESEG SEGMENT 'CODE'
    ASSUME SS:STACKSG, DS:DATASG, CS:CODESG
    MAIN PROC FAR
        MOV AX, DATASG;
        MOV DS,AX;
        LEA SI, DATA_IN; 
        LEA DI, COPY1;
        MOV CL,5;
        BACK1: MOV AL, [SI];
        MOV [DI], AL;
        INC DI;
        INC SI;
        DEC CL;
        JNZ BACK1;
        MOV AX, 4C00H;
        INT 21H;
        MAIN ENDP;
    CODESEG ENDS;
END MAIN;





